### ISSUE TITLE
Setting particle ID in save_initial_distribution

### ISSUE THREAD

**Issue by ColwynGulliford** [electronsandstuff/easygdf#1]
The new version looks awesome.  One use case that looks like it might be missing is setting the particle ID numbers.  This is actually used by people in BBL, when they are looking at core charges vs. shield charges and what have you.  Its also useful for directly computing the particle trajectories (GPT has a method for that, but with easygdf, its basically just as easy to form the trajectories oneself in python).  Can this be added?  Or is it already there?  I didn't see it in:

save_initial_distribution(f, x=None, y=None, z=None, GBx=None, GBy=None, GBz=None, ...)

Saves GPT compatible initial distribution file. All array objects must be the same length (IE the number of particles). If required values (either {x, y, z, GBx, GBy, GBz} or {x, y, z, Bx, By, Bz}) are missing, easyGDF will autofill them with zeros. Only specify the momentum or the velocity of particles, not both.

Parameters

f: filename or open file/stream-like object
x (default: None): numpy array, particle position
y (default: None):numpy array, particle position
z (default: None):numpy array, particle position
GBx (default: None):numpy array, particle momentum
GBy (default: None):numpy array, particle momentum
GBz (default: None):numpy array, particle momentum
Bx (default: None):numpy array, particle velocity
By (default: None):numpy array, particle velocity
Bz (default: None):numpy array, particle velocity
t (default: None):numpy array, particle spawn time
G (default: None):numpy array, Lorentz factor
m (default: None):numpy array, particle mass
q (default: None):numpy array, particle charge
nmacro (default: None):numpy array, number of macroparticles
rmacro (default: None):numpy array, macroparticle size
creation_time (default: current time): int/datetime object creation time written to header (default: time when file is written)
creator (default: "easygdf"): string written to header
destination (default: ""): string written to header
gdf_version (default: (1, 1)): tuple (int, int) written to header. (Don't change unless you like messing with low-level stuff)
creator_version (default: (2, 0)): tuple (int, int) written to header
destination_version (default: (0, 0)): tuple (int, int) written to header
dummy (default: (0, 0)): tuple (int, int) written to header
max_recurse (default: 16): Maximum recursion depth while saving blocks in GDF file

**Comment by electronsandstuff** [comment]
Added in commit 6ca5cf110475631e2dcd0088b0150f5e46231335.  For some reason particle IDs were not mentioned in the GPT documentation used to make the function.

Also added ability to insert arbitrary named arrays into initial distribution files through keyword arguments just in case other important parameters are not included.
