### ISSUE TITLE
Incorrect usage of assert for error detection

### ISSUE THREAD

**Issue by st-walker** [electronsandstuff/easygdf#3]
Just to let you know in easygdf.py for example, this use of assert below is incorrect, if someone runs in `-O` or `-OO` mode (not entirely unreasonable) then these asserts will never be run, and the error will be handed in an unpredictable way.  This is elsewhere in the code as well.  There should be a class inheriting Exception like `GDFIOError` (say) and that should be raised instead, so the user can maybe catch this, whereas catching an AssertionError is not a good idea.  assert should really just be used as an interactive comment/sanity check I would say.  Just something I noticed.  Thanks for writing this nice package anyway, saved me some time this week.

```   
assert isinstance(f, io.BufferedReader)
f.read(1)  # Trigger any IO errors here
assert is_gdf(f)
```

**Comment by electronsandstuff** [comment]
Glad to hear somebody is using the package.  Didn't know that asserts weren't correct here.   Looks like a simple fix, however, and I can take a look at it in the next few days.

**Comment by electronsandstuff** [comment]
Solved with linked pull request
